"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TelegramBot = exports.TelegramService = exports.MaxBot = exports.MaxService = void 0;
var Service_1 = require("./max/Service.js");
Object.defineProperty(exports, "MaxService", { enumerable: true, get: function () { return Service_1.Service; } });
var Bot_1 = require("./max/Bot.js");
Object.defineProperty(exports, "MaxBot", { enumerable: true, get: function () { return Bot_1.MaxBot; } });
var Service_2 = require("./telegram/Service.js");
Object.defineProperty(exports, "TelegramService", { enumerable: true, get: function () { return Service_2.Service; } });
var Bot_2 = require("./telegram/Bot.js");
Object.defineProperty(exports, "TelegramBot", { enumerable: true, get: function () { return Bot_2.TelegramBot; } });
